server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlaaBrahim/microservice-spring-cloud.git
          clone-on-start: true
          search-paths: configs
          default-label: circuit-breaker # Specify the branch to pull from
    compatibility-verifier:
      enabled: false
